### ISSUE TITLE
Confused on yesterday's comments

### ISSUE THREAD

**Issue by michael4180** [michael4180/WeatherApp#15]
@bbelderbos Hi Bob, a bit confused on the comments around git you provided yesterday.  I feel like I need to review with you on friday the comments to better understand.  We can also review the other comments as well to make sure I'm following.

**Comment by bbelderbos** [comment]
Yeah sorry, I realized it might not have been too clear because I need to better understand how you use git. Let's discuss it tomorrow. Meanwhile have you progressed more with the project and/or bites?

**Comment by bbelderbos** [comment]
That's funny you mention that. Another PDI-er ran into the same issue of GUIs being too limited as he needed to show a map to retrieve geolocations and pivoted to Flask. I find web apps easier to manager and more versatile, also with deployment. So I am happy for you to move to Flask for this, I think it's more useful. Discuss later ...
