### ISSUE TITLE
Template Folder and Flask_APP

### ISSUE THREAD

**Issue by michael4180** [michael4180/WeatherApp#16]
@bbelderbos  Hi bob, set up a web page using flask to run my weather app!  it works!  I added and pushed the new update i did to the new-gui-feature branch and I see the update in github.  But for some reason i'm not being notfied by github to compare and push so i can send the update to you.  Not sure why, but wanted to let you know.  Speak to you tomorrow..thx

**Comment by bbelderbos** [comment]
Awesome, yeah I only got emails about new commits on existing branch, but I will review now - this is how it looks for me:

<img width="1005" alt="image" src="https://github.com/michael4180/WeatherApp/assets/387927/ff6b7aaf-4c03-4c00-b8cd-d7ef029e7c41">

Let's merge all into main on our call later today and then from there on you'll do this locally:

```
git checkout main  # got to main branch if not already on there
git pull origin main  # get changes from github, main is further ahead there because you merged in all pull requests
git checkout -b new-brach  # create and go onto new branch (name it something something more meaningful)
# do work
git add .
git commit -m "..."
git push origin new-branch
# open PR on github
```

**Comment by bbelderbos** [comment]
flask env file commited here: https://github.com/michael4180/WeatherApp/commit/c013442e716f76b63baf89998b6b50a5fa40297e
