### ISSUE TITLE
code feedback and next steps

### ISSUE THREAD

**Issue by bbelderbos** [michael4180/WeatherApp#5]
nice work!
https://github.com/michael4180/WeatherApp/blob/initial_setup/weather_app.py

- where is config.py? `from config import openweather_api_key as api_key` but I don't see this module, best practice is to use environment variables and an .env file, see [How to handle environment variables in Python](https://pybit.es/articles/how-to-handle-environment-variables-in-python/) < most important thing is to separate config from code and for sensitive data like the api key to not be committed to version control

- I'd also use upper case for this constant as well as base_url which you could break out of the function

- you can add exception handling in case the api does not respond (requests.raise_for_status) but you kind of do that in display_weather by checking the key (what is "cod" btw)? 

- nicely modular, also you used if __name__ == "__main__": - is that clear now? If not check my video: https://www.youtube.com/watch?v=ubpFY7_dAW4

- add a requirements.txt file for dependencies, in this case requests, you can use pip-tools, see my two videos (also on how to start a project):

-> [Using pip-tools to manage Python dependencies](https://www.youtube.com/watch?v=G8PApVvdkjQ)
-> [Starting a Python project - poetry, pip-tools, git + GitHub, package or not?](https://www.youtube.com/watch?v=sp48IVe6SqQ) 

- you can use flake8/black or ruff for linting / auto-formatting, it would be useful to run these tools automatically upon commit, see https://www.youtube.com/watch?v=XFyLzr5Ehf0

- next steps? here are some ideas:

-> validate user enters a valid city 
-> display a 5-day forecast in addition to the current weather
-> display weather alerts or warnings for the specified area
-> allow users to optionally use their current location for weather updates instead of entering a city name
-> wrap this app in a gui or flask web app
-> option for users to show temperature in Fahrenheit or Celsius
-> view historical weather data for a given date and location (requires persist data into a database)
->integrate weather maps that can show weather data (e.g. precipitation, temperature, and wind information) graphically

please pick one or two and open issues for the next features ...

HTH
Bob

**Comment by michael4180** [comment]
@bbelderbos Hi, I put the config file inthe .gitignore folder.  Is that not correct?

I'll work on cleaning up the branch issue to see if i can fix.  

I'm also going to work on adding more functionality like you suggested.  

I'll work on getting to your other suggestions asap..thx

**Comment by michael4180** [comment]
@bbelderbos "cod" is short for code.  thx

**Comment by michael4180** [comment]
@bbelderbos added a 5 day forecast and set up another branch.  I think I did this right but let me know if something looks off.  That's all i can do tonight.  Off to bed!  beat!

**Comment by bbelderbos** [comment]
Great progress, I will review. Yes putting config in .gitignore is correct, but there is a better way of doing it using a library + .env file, see mentioned article. Cheers

**Comment by bbelderbos** [comment]
probably done, new code to be reviewed on new branches and pull requests ... 
keep going, great work! @michael4180
